#If this box is not on your machine, vagrant up base and make that a base box. Then add that to vagrant
$cent_box = "geerlingguy/centos7"

def medium(config)
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
end

def large(config)
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048 
      v.cpus = 2
    end
end

Vagrant.configure(2) do |config|

    config.vm.define "gem_master" do |build_boot|
        large(config)
        build_boot.vm.box = $cent_box
        build_boot.vm.hostname = "gem-master01"
        build_boot.vm.network "private_network", ip: "10.10.10.10", virtualbox__intnet: "prov"
        build_boot.vm.provision :shell, path: "provision_scripts/packages.sh"
        build_boot.vm.provision :shell, path: "provision_scripts/docker.sh", privileged: false
        #build_boot.vm.provision :shell, path: "provision_scripts/build.sh", privileged: false
        #build_boot.vm.provision :shell, path: "provision_scripts/cluster-prep.sh", privileged: false
        #build_boot.vm.provision :shell, path: "provision_scripts/dnsmasq.sh"
    end
end
